#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: build-pr-check

on: 
  push:
    branches:
      - master

jobs:
#  build:
#    runs-on: ubuntu-20.04
#    steps:
#    - uses: actions/checkout@v2
#    - name: Cache local Maven repository
#      uses: actions/cache@v2
#      with:
#       path: ~/.m2/repository
#       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#       restore-keys: |
#        ${{ runner.os }}-maven-      
#    - name: Set up JDK 11
#      uses: actions/setup-java@v1
#      with:
#        java-version: 11
#    - name: Build with Maven
#      run: mvn -B clean install -U -Pintegration

  build-on-z:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch:
          - amd64
          - s390x
    steps:
      - uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven- 
      - name: Update System
        run: sudo apt-get update -y
      - name: Install qemu
        run: sudo apt-get install -y --no-install-recommends qemu-user-static
      - name: Experimental Docker
        run: sudo cp .github/experimental-docker.json /etc/docker/daemon.json
      - name: Restart Docker
        run: sudo systemctl restart docker.service
      - name: Pull docker image
        run: docker pull --platform $(echo ${{ matrix.arch }} | sed 's|-|/|g') debian:10 || true
      - name: Build inside Docker
        run: docker run --rm -v $GITHUB_WORKSPACE:/work debian:10 /work/.github/build-native-debian.sh
      
